volumes:
    directus-database:
    directus-uploads:
    directus-extensions:

services:
    directus:
        image: directus/directus:11.5.1
        # ports:
        #     - 8055:8055
        volumes:
            - directus-database:/directus/database
            - directus-uploads:/directus/uploads
            - directus-extensions:/directus/extensions
        environment:
            SECRET: ${DIRECTUS_SECRET}
            ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
            ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
            DB_CLIENT: "sqlite3"
            DB_FILENAME: "/directus/database/data.db"
            WEBSOCKETS_ENABLED: "true"
  
    frontend:
        image: ghcr.io/nicolassutter/portfolio/portfolio-astro:latest
        environment:
            DIRECTUS_ADMIN_TOKEN: ${DIRECTUS_ADMIN_TOKEN}
            PORT: 3000
            HOST: "0.0.0.0"
