backend:
  name: github
  repo: nicolassutter/portfolio
  branch: main
  site_domain: sutter-nicolas.com # change this to your domain
  base_url: https://sutter-nicolas.com # change this to your prod URL
  auth_endpoint: oauth # the oauth route provided by the integration

media_folder: "packages/frontend/public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "packages/frontend/src/content/posts"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "publishedAt", label: "Published At", widget: "datetime", required: false }
      - { name: "tags", label: "Tags", widget: "list", required: false }
      - { name: "category", label: "Category", widget: "string", required: false }
      - { name: "lang", label: "Language", widget: "select", options: ["en", "fr"] }
      - { name: "thumbnail", label: "Thumbnail", widget: "image", allow_multiple: false }
      - label: "ID"
        name: "id"
        widget: "uuid"
      - { name: "date_created", label: "Date Created", widget: "datetime", required: false }
      - { name: "date_updated", label: "Date Updated", widget: "datetime", required: false }
      - { name: "status", label: "Status", widget: "select", options: ["published", "draft"], required: false }
      - { name: "order", label: "Order", widget: "number" }
      - { name: "body", label: "Content", widget: "markdown", required: false }


