name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: portfolio-minoro

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Git SHA for image tag
        id: extract_sha
        run: echo "SHA_TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: minoro.Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ steps.extract_sha.outputs.SHA_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

